"""Assemble Chapter 4 (Main).md from the 9 branch files + figures.

Improvements over the first pass:
- Read branches as raw bytes, normalize cp1252 punctuation (0x97 em-dash,
  0x96 en-dash, 0x91-94 curly quotes, 0x85 ellipsis) to proper UTF-8 BEFORE
  decoding.
- Strip ALL line-ending variants (\\r\\n, \\r, \\n) and treat the document as
  paragraphs separated by blank lines.
- Within a callout block (line starting with '>'), MERGE every orphan
  continuation line into the previous '>' line so it stays inside the
  callout. NotebookLM hard-wraps at ~80 chars but only prefixes the first
  line of each wrap with '>', which made the second line render as
  out-of-callout plain text.
- Write the final file in BINARY mode with explicit \\n line endings so
  Windows text mode doesn't double-encode them as \\r\\n.
"""
import re
import os

DIR = os.path.dirname(os.path.abspath(__file__))

BRANCHES = [
    ('4_1_exponential_functions',  '4.1 Exponential Functions'),
    ('4_2_graphs_of_exponential',  '4.2 Graphs of Exponential Functions'),
    ('4_3_logarithmic_functions',  '4.3 Logarithmic Functions'),
    ('4_4_graphs_of_logarithmic',  '4.4 Graphs of Logarithmic Functions'),
    ('4_5_logarithmic_properties', '4.5 Logarithmic Properties'),
    ('4_6_equations',              '4.6 Exponential and Logarithmic Equations'),
    ('4_7_models',                 '4.7 Exponential and Logarithmic Models'),
    ('4_8_fitting_models',         '4.8 Fitting Exponential Models to Data'),
    ('chapter_review',             'Chapter Review'),
]

FIGURE_EMBEDS = {
    '4_1_exponential_functions': (
        '![Exponential growth and decay parent curves](pc4_fig1_exp_growth_decay.png)\n'
        '*Generated by matplotlib via `_gen_pc4_fig1_exp_growth_decay.py` — Two parent '
        'exponential curves on shared axes, both passing through $(0,\\,1)$. The blue curve '
        '$f(x) = 2^x$ ($b > 1$) grows without bound; the copper curve $g(x) = (1/2)^x$ '
        '($0 < b < 1$) decays toward the horizontal asymptote $y = 0$.*\n'
    ),
    '4_3_logarithmic_functions': (
        '![The log function as the reflection of the exponential over y=x](pc4_fig2_log_inverse_of_exp.png)\n'
        '*Generated by matplotlib via `_gen_pc4_fig2_log_inverse_of_exp.py` — The logarithm '
        '$\\log_2 x$ is the reflection of $2^x$ across the diagonal $y = x$. A point $(a,\\,b)$ '
        'on the exponential corresponds to the point $(b,\\,a)$ on the logarithm.*\n'
    ),
    '4_4_graphs_of_logarithmic': (
        '![Log curves for several bases](pc4_fig3_log_bases.png)\n'
        '*Generated by matplotlib via `_gen_pc4_fig3_log_bases.py` — Logarithm curves for '
        'base 2, base $e$ (natural), and base 10 (common). All share the universal anchor '
        '$(1,\\,0)$ and the vertical asymptote $x = 0$. Smaller bases produce steeper curves.*\n'
    ),
    '4_7_models': (
        '![Half-life decay with marked halvings](pc4_fig4_half_life_decay.png)\n'
        '*Generated by matplotlib via `_gen_pc4_fig4_half_life_decay.py` — Radioactive '
        'decay $N(t) = N_0\\,(1/2)^{t/T_{1/2}}$ with half-life $T_{1/2} = 5$. The quantity '
        'halves on every fixed interval, approaching but never reaching zero.*\n\n'
        '![Logistic growth with carrying capacity](pc4_fig5_logistic_growth.png)\n'
        '*Generated by matplotlib via `_gen_pc4_fig5_logistic_growth.py` — Logistic growth '
        'bends an exponential curve into an S-shape as it approaches a carrying capacity $K$. '
        'The inflection point at $P = K/2$ is where the population is growing fastest.*\n'
    ),
}

# cp1252 -> UTF-8 byte-level normalization (run on raw bytes BEFORE decode)
CP1252_FIXES = [
    (b'\x85', '…'.encode('utf-8')),
    (b'\x91', '‘'.encode('utf-8')),
    (b'\x92', '’'.encode('utf-8')),
    (b'\x93', '“'.encode('utf-8')),
    (b'\x94', '”'.encode('utf-8')),
    (b'\x95', '•'.encode('utf-8')),
    (b'\x96', '–'.encode('utf-8')),
    (b'\x97', '—'.encode('utf-8')),
]


def read_clean_branch(slug: str) -> str:
    """Read a branch file, normalize cp1252 bytes, decode, normalize line endings."""
    path = os.path.join(DIR, f'_branch_{slug}.md')
    with open(path, 'rb') as f:
        raw = f.read()
    for bad, good in CP1252_FIXES:
        raw = raw.replace(bad, good)
    text = raw.decode('utf-8', errors='replace')
    # Replace any remaining U+FFFD with em-dash (the only bad byte we saw was 0x97)
    text = text.replace('�', '—')
    # Normalize line endings: \r\n and \r → \n
    text = text.replace('\r\n', '\n').replace('\r', '\n')
    return text


def strip_artifacts(text: str) -> str:
    """Strip NotebookLM artifacts (citations, leading 'Answer:', stray quotes after em-dash)."""
    # Drop a leading 'Answer:' or 'Continuing conversation...' line if present
    lines = text.split('\n')
    while lines and lines[0].strip() in {'', 'Answer:'}:
        lines = lines[1:]
    # Drop trailing chat continuation lines
    while lines and (
        lines[-1].strip().startswith('Resumed conversation:') or
        lines[-1].strip().startswith('Continuing conversation') or
        lines[-1].strip() == ''
    ):
        lines = lines[:-1]
    text = '\n'.join(lines)
    # Strip NotebookLM citation tags like " [1]", " [1, 2]"
    text = re.sub(r'\s*\[\d+(?:,\s*\d+)*\]', '', text)
    # Strip stray closing-quote artifacts adjacent to em-dashes
    text = re.sub(r'—\s*["”“]\s*', '— ', text)
    return text.strip()


def fix_callout_continuations(text: str) -> str:
    """Glue orphan continuation lines into the preceding callout '>' line.

    NotebookLM hard-wraps text at ~80 cols but only the first wrapped line
    gets the '>' prefix. The remaining lines render as plain text outside
    the callout. Fix: merge them into the previous line until we hit either
    a blank line (callout ends) or another '>' line.
    """
    lines = text.split('\n')
    out = []
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith('>'):
            # Inside a callout. Accumulate this line + any orphan continuations.
            merged = line.rstrip()
            j = i + 1
            while j < len(lines):
                nxt = lines[j]
                if nxt.strip() == '' or nxt.startswith('>'):
                    break
                # Orphan continuation — append with single space separator
                merged = merged.rstrip() + ' ' + nxt.strip()
                j += 1
            out.append(merged)
            i = j
        else:
            out.append(line)
            i += 1
    return '\n'.join(out)


def insert_figures(branch_text: str, slug: str) -> str:
    """Insert the section's figures right after the intro paragraph (before first callout)."""
    if slug not in FIGURE_EMBEDS:
        return branch_text
    figure_block = FIGURE_EMBEDS[slug]
    lines = branch_text.split('\n')
    insert_idx = None
    for i, line in enumerate(lines):
        if line.lstrip().startswith('> [!'):
            insert_idx = i
            break
    if insert_idx is None:
        return branch_text + '\n\n' + figure_block
    return '\n'.join(lines[:insert_idx]) + '\n\n' + figure_block + '\n' + '\n'.join(lines[insert_idx:])


# ===========================================================================
# Build the Main file
# ===========================================================================
HEADER = """---
title: "Precalculus 2e — Chapter 4: Exponential and Logarithmic Functions"
---

# Chapter 4 — Exponential and Logarithmic Functions

*Companion note to OpenStax Precalculus 2e, Chapter 4. Paraphrased summary built through NotebookLM; figures generated by matplotlib. Excludes the chapter's exercise problem set.*

| Field | Value |
|---|---|
| **Source** | [OpenStax Precalculus 2e](https://openstax.org/details/books/precalculus-2e) |
| **Pages covered** | 407–534 (sections 4.1 through Chapter Review; exercises 535–544 excluded) |
| **Chapter scope** | Exponential functions, logarithms, their graphs, properties, equations, models, curve-fitting |
| **License** | CC-BY 4.0 (this note is a paraphrased derivative work with attribution) |

![Chapter 4 concept map](pc4_mindmap.png)

---

## At a glance

Chapter 4 covers the two complementary function families that show up nearly everywhere non-linear: **exponential functions** (where the variable is the exponent — modeling compound growth and decay) and **logarithmic functions** (their inverse — extracting an exponent given the result). The chapter builds from concrete arithmetic (compound interest, half-life) through algebraic manipulation (log properties, equation solving) to applied modeling (curve-fitting to real data).

The central narrative thread: anywhere a quantity changes by a constant **percentage** per unit time (rather than a constant amount), an exponential function fits, and its inverse logarithm gives you back the time. Half-life, doubling time, pH, decibels, Richter, compound interest, drug dosing, population growth — all the same machinery applied to different domains.

---
"""

FOOTER = """
---

## Key takeaways

1. **Exponential functions $f(x) = ab^x$** model anything that grows or decays by a *constant percentage* per unit time — the multiplicative counterpart of linear addition. The base $b$ controls direction: $b > 1$ grows, $0 < b < 1$ decays. The initial value $a$ is the $y$-intercept.
2. **The number $e \\approx 2.71828$** emerges naturally as the limit of $(1 + 1/n)^n$ — the asymptote of compound-interest yield as the compounding period shrinks to zero. Continuous models use $A(t) = A_0\\,e^{rt}$.
3. **Logarithms are the inverse of exponentials.** The statement $\\log_b x = y$ is equivalent to $b^y = x$. Common logarithms use base 10; natural logarithms use base $e$. The two bases that get their own notation are the two with applications all over physics, engineering, and finance.
4. **Three log properties — product, quotient, power — plus change-of-base** are the algebraic toolkit. They convert multiplications into additions, divisions into subtractions, and powers into multiplications. This is exactly why logarithm tables (and slide rules) ran much of pre-electronic computation.
5. **Solving exp/log equations** uses either the one-to-one property (equate exponents or arguments directly when the bases match) or "take log of both sides" (when they don't). Always re-check candidate solutions against the domain — logarithm arguments must stay positive, so extraneous solutions can appear.
6. **Real-world models** built from this machinery: half-life decay, Newton's law of cooling, doubling time, and the logistic S-curve (an exponential bent by a carrying capacity). Each carries the same skeleton — exponential with a context-specific rate.
7. **Fitting models to data** uses exponential or logarithmic regression on a scatter plot. The correlation coefficient $r$ reports the linearity of the transformed data; the model is good when $r$ is close to $\\pm 1$.

---

## Related documents

- **[[Logarithm Fundamentals (Main)]]** — companion note (different source, more conceptual / 3Blue1Brown-style angle). Pair §4.3–4.5 of this chapter with that note for the intuitive picture beside the textbook treatment.
- **[[Imaginary Interest and Continuous Rotation (Main)]]** — same compound-interest → $e$ derivation that anchors §4.1, but extended into the complex plane where it becomes simple harmonic motion. The natural next step once you understand why $e$ is the right base.

---

## Sources & attribution

| Source | Type | Pages | License |
|---|---|---|---|
| [OpenStax Precalculus 2e — Chapter 4](https://openstax.org/details/books/precalculus-2e) | Textbook | 407–534 | CC-BY 4.0 |

This note paraphrases content from OpenStax Precalculus 2e, Chapter 4, under the [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/). All worked examples, definitions, and formulas are restated in paraphrased form; figures are generated programmatically via matplotlib rather than extracted from the source. The original book is freely available at [openstax.org](https://openstax.org/details/books/precalculus-2e).
"""

# Process each branch: read clean, strip artifacts, fix callouts, insert figures.
sections = []
for slug, _title in BRANCHES:
    text = read_clean_branch(slug)
    text = strip_artifacts(text)
    text = fix_callout_continuations(text)
    text = insert_figures(text, slug)
    sections.append(text)

main_content = HEADER + '\n'.join(sections) + FOOTER

# Final cleanup: collapse runs of more than 2 consecutive newlines down to 2.
main_content = re.sub(r'\n{3,}', '\n\n', main_content)

# Write in BINARY mode with explicit \n so Windows doesn't auto-convert to \r\n.
main_path = os.path.join(DIR, 'Chapter 4 (Main).md')
with open(main_path, 'wb') as f:
    f.write(main_content.encode('utf-8'))

# Sanity checks
data = open(main_path, 'rb').read()
word_count = len(main_content.split())
line_count = main_content.count('\n')
crlf_count = data.count(b'\r\n')
ufffd_count = data.count(b'\xef\xbf\xbd')
size_kb = os.path.getsize(main_path) / 1024

print('Chapter 4 (Main).md regenerated')
print(f'  Words : {word_count:,}')
print(f'  Lines : {line_count:,}')
print(f'  Size  : {size_kb:.1f} KB')
print(f'  CRLF  : {crlf_count}  (should be 0)')
print(f'  U+FFFD: {ufffd_count} (should be 0)')

# Verify no orphan continuations remain
lines = main_content.split('\n')
orphans = 0
in_callout = False
for ln in lines:
    if ln.startswith('>'):
        in_callout = True
    elif ln.strip() == '':
        in_callout = False
    elif in_callout:
        orphans += 1
print(f'  Orphan continuations remaining: {orphans} (should be 0)')
